flask_internals/models.py
"""Database models."""
from . import db
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    """User account model."""

    __tablename__ = 'flasklogin-users'
    id = db.Column(
        db.Integer,
        primary_key=True
    )
    name = db.Column(
        db.String(100),
        nullable=False,
        unique=False
    )
    email = db.Column(
        db.String(40),
        unique=True,
        nullable=False
    )
    password = db.Column(
        db.String(200),
        primary_key=False,
        unique=False,
        nullable=False
    )
    

    def set_password(self, password):
        """Create hashed password."""
        self.password = generate_password_hash(password, method='sha256')

    def check_password(self, password):
        """Check hashed password."""
        return check_password_hash(self.password, password)

    def __repr__(self):
        return '<User {}>'.format(self.username)

flask_internals/forms.py
"""Sign-up & log-in forms."""
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, Length, Optional


class LoginForm(FlaskForm):
    """User Log-in Form."""
    email = StringField(
        'Email',
        validators=[
            DataRequired(),
            Email(message='Enter a valid email (example@eatery.co.il)')
        ]
    )
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Log In')


class GetEmailForm(FlaskForm):
    "Get Email From."
    email = StringField(
        'Email',
        validators=[
            DataRequired(),
            Email(message='Enter a valid email.')
        ]
    )
    submit = SubmitField("Reset Password")


class SignupForm(FlaskForm):
    """User Sign-up Form."""
    name = StringField(
        'Name',
        validators=[DataRequired()]
    )
    email = StringField(
        'Email',
        validators=[
            Length(min=6),
            Email(message='Enter a valid email (example@eatery.co.il)'),
            DataRequired()
        ]
    )
    password = PasswordField(
        'Password',
        validators=[
            DataRequired(),
            Length(min=6, message='Select a stronger password.')
        ]
    )
    confirm = PasswordField(
        'Confirm Your Password',
        validators=[
            DataRequired(),
            EqualTo('password', message='Passwords must match.')
        ]
    )
    submit = SubmitField('Register')

flask_internals/__init__.py
"""Initialize app."""
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager


db = SQLAlchemy()
login_manager = LoginManager()


def create_app():
    """Construct the core app object."""
    app = Flask(__name__, instance_relative_config=False)
    app.config.from_object('config.Config')
  
    # Initialize Plugins
    db.init_app(app)
    login_manager.init_app(app)

    with app.app_context():
        from . import routes
        #from .assets import compile_static_assets

        # Register Blueprints
        app.register_blueprint(routes.main_bp)
      #  app.register_blueprint(auth.auth_bp)

        # Create Database Models
        db.create_all()
        return app

flask_internals/routes.py
from flask import (Blueprint, render_template, flash, redirect, url_for,
                   request, abort, session, send_from_directory, render_template_string)
from .forms import LoginForm, GetEmailForm, SignupForm
from flask_login import current_user, login_user, login_required, logout_user
from . import login_manager
from .models import db, User

# Blueprint Configuration
main_bp = Blueprint('main_bp',
                    __name__,
                    template_folder='templates',
                    static_folder='static')


@main_bp.route('/')
def main():
    return render_template('index.html')

@main_bp.route('/robots.txt')
def load_robots_txt():
    return main_bp.send_static_file('robots.txt')

@main_bp.route('/secret.txt')
def load_secret_txt():
    return render_template('secret.html')

@main_bp.route('/config')
def load_config_file():
    return render_template('config.html')

@main_bp.route('/todo.txt')
def load_todo_list():
    return  main_bp.send_static_file('todolist.txt')

@main_bp.route('/Management/')
def load_management():
    return redirect(url_for('main_bp.load_management_login'))


@main_bp.route('/Management/testlogin')
def load_management_login():
    return render_template('login_page_test.html')

# Needs another bruteforce in order to get to the login form.
@main_bp.route('/Management/login_form')
def load_management_admin():
    return redirect(url_for('main_bp.load_admin_login'))

# Here is the admin login page.
@main_bp.route('/Management/login_form/admin_login_v2/login', methods=['GET', 'POST'])
def load_admin_login():
    """Log-in page for registered users.
    GET requests serve Log-in page.
    POST requests validate and redirect user to dashboard."""
  
    form = LoginForm()

    if form.validate_on_submit():
        # check for a specifc email and password
        # in order to avoid SQL injection etc..
        if form.email.data == "admin@eatery.co.il" and form.password.data == "Password1":
            user = User.query.filter_by(email=form.email.data).first()
            login_user(user)
            return redirect(url_for('main_bp.dashboard'))

        flash('Invalid email/password')
        return redirect(url_for('main_bp.load_admin_login'))

    return render_template(
        'admin_login/login.jinja2',
        form=form,
        title='Log in - Eatery Cafe',
        template='login-page',
        body="Log in with your User account."
    )

@main_bp.route('/Management/login_form/admin_login_v2/signup', methods=['GET', 'POST'])
def signup():
    """User sign-up page.
    GET requests serve sign-up page.
    POST requests validate form & user creation."""

    form = SignupForm()

    if form.validate_on_submit():
        existing_user = User.query.filter_by(email=form.email.data).first()
        if existing_user is None:
            return redirect(url_for('main_bp.load_admin_login'))

        flash('A user already exists with that email address.')
        
    return render_template(
        'admin_login/signup.jinja2',
        title='Create an Account',
        form=form,
        template='signup-page',
        body="Sign up for a user account."
    )
    
@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in upon page load."""
    if user_id is not None:
        return User.query.get(user_id)
    return None

@login_manager.unauthorized_handler
def unauthorized():
    """Redirect unauthorized users to Login page."""
    flash('You must be logged in to view that page.')
    return redirect(url_for('main_bp.load_admin_login'))

# loading the dashboard, after login.
@main_bp.route('/Management/login_form/admin_login_v2/dashboard/index.html', methods=['GET', 'POST'])
@login_required
def dashboard():
    return render_template('dashboard/index.html')

@main_bp.route('/Management/login_form/admin_login_v2/dashboard/ui-maps.html')
def load_maps():
    return render_template('dashboard/ui-maps.html')

@main_bp.route('/Management/login_form/admin_login_v2/dashboard/ui-icons.html')
@login_required
def load_icons():
    return render_template('dashboard/ui-icons.html')

@main_bp.route('/Management/login_form/admin_login_v2/dashboard/ui-notifications.html')
@login_required
def load_nof():
    return render_template('dashboard/ui-notifications.html')

@main_bp.route('/Management/login_form/admin_login_v2/dashboard/page-user.html')
@login_required
def load_page_user_html():
    return render_template('dashboard/page-user.html')

# ------------------------------------------------------- #
# The Important Part - SSTI - inject payload in order to get the private keys.
@main_bp.route("/Management/login_form/admin_login_v2/dashboard/register", methods=['GET', 'POST'])
def load_register_ssti():
    content = request.args.get("register")
    if content:
        return render_template_string(content)
    return render_template('dashboard/accounts/register.html')


@main_bp.route("/logout")
@login_required
def logout():
    """User log-out."""
    logout_user()
    return redirect(url_for('main_bp.load_admin_login'))

flask_internals/templates/admin_login/login.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="form-wrapper">
  {% for message in get_flashed_messages() %}
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %}
  <h1>Log in - Eatery Cafe</h1>
  <form method="POST" action="/Management/login_form/admin_login_v2/login">
    {{ form.csrf_token }}
    <fieldset class="email">
      {{ form.email.label }}
      {{ form.email(placeholder='example@eatery.co.il') }}
      {% if form.email.errors %}
      <ul class="errors">
        {% for error in form.email.errors %}
        <li>{{ error }}</li>{% endfor %}
      </ul>
      {% endif %}
    </fieldset>

    <fieldset class="password">
      {{ form.password.label }}
      {{ form.password }}
      {% if form.email.errors %}
      <ul class="errors">
        {% for error in form.password.errors %}
        <li>{{ error }}</li>{% endfor %}
      </ul>
      {% endif %}
    </fieldset>

    <div class="submit-button">
      {{ form.submit }}
    </div>
    
    <div class="login-signup">
      <p><span><a href="{{ url_for('main_bp.signup') }}">Don't have an account?</a></span></p>
    </div>
  </form>
</div>
{% endblock %}

flask_internals/templates/admin_login/signup.jinja2
{% extends "layout.jinja2" %}

{% block pagestyles %}
<link href="{{ url_for('static', filename='css/account.css') }}" rel="stylesheet" type="text/css">
{% endblock %}

{% block content %}
<div class="form-wrapper">
  {% for message in get_flashed_messages() %}
  <div class="alert alert-warning">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    {{ message }}
  </div>
  {% endfor %}

  <h1>Sign Up</h1>

  <form method="POST" action="/Management/login_form/admin_login_v2/signup">
    {{ form.csrf_token }}

    <fieldset class="name">
      {{ form.name.label }}
      {{ form.name(placeholder='') }}
      {% if form.name.errors %}
      <ul class="errors">
        {% for error in form.email.errors %}
        <li>{{ error }}</li>{% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <fieldset class="email">
      {{ form.email.label }}
      {{ form.email(placeholder='example@eatery.co.il') }}
      {% if form.email.errors %}
      <ul class="errors">
        {% for error in form.email.errors %}
        <li>{{ error }}</li>{% endfor %}
      </ul>
      {% endif %}
    </fieldset>

    <fieldset class="password">
      {{ form.password.label }}
      {{ form.password }}
      {% if form.password.errors %}
      <ul class="errors">
        {% for error in form.password.errors %}
        <li>{{ error }}</li>{% endfor %}
      </ul>
      {% endif %}
    </fieldset>

    <fieldset class="confirm">
      {{ form.confirm.label }}
      {{ form.confirm }}
      {% if form.confirm.errors %}
      <ul class="errors">
        {% for error in form.confirm.errors %}
        <li>{{ error }}</li>{% endfor %}
      </ul>
      {% endif %}
    </fieldset>
    <div class="submit-button">
      {{ form.submit }}
    </div>
  </form>
  <div class="login-signup">
    <span><a href="{{ url_for('main_bp.load_admin_login') }}"> Already have an account?</a></span>
  </div>
</div>
{% endblock %}

flask_internals/templates/base.html
<!--
=========================================================
* * Black Dashboard - v1.0.1
=========================================================

* Product Page: https://www.creative-tim.com/product/black-dashboard
* Copyright 2019 Creative Tim (https://www.creative-tim.com)


* Coded by Creative Tim

=========================================================

* The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-->
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="../static/assets/img/apple-icon.png">
  <link rel="icon" type="image/png" href="../static/assets/img/favicon.png">
  <title>
    Flask Dashboard Black - {% block title %}{% endblock %} | AppSeed
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="/static/assets/css/nucleo-icons.css" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="/static/assets/css/black-dashboard.css?v=1.0.0" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="/static/assets/demo/demo.css" rel="stylesheet" />

  <!-- Specific Page CSS goes HERE  -->
  {% block stylesheets %}{% endblock stylesheets %}

</head>

<body class="">
  <div class="wrapper">

    {% include 'includes/sidebar.html' %}

    <div class="main-panel">

      {% include 'includes/navigation.html' %}

      <div class="content">

        {% block content %}{% endblock content %}

      </div>


    </div>

  </div>
  {% include 'includes/fixed-plugin.html' %}
  {% include 'includes/scripts.html' %}
  {% include 'includes/scripts-sidebar.html' %}
  {% block javascripts %}{% endblock javascripts %}
</body>

</html>

flask_internals/templates/base_admin.html
<html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" type="text/javascript"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}" />
    <script src="{{ url_for('static', filename='script.js') }}" type="text/javascript"></script>
</head>

<body>
    <div id="main">
        <div id="navbar">
            <ul>
                <li><a id="login" href="/login">Login</a></li>
            </ul>
        </div>

        <br><br><br><br>

        {% block content %}
        {% endblock %}
    </div>

</body>

</html>

flask_internals/templates/config.html
<html>

<body>
    <!-- Don't forget to remove config file before production!!! -->
    <p>
        <!-- configuration -->
        ENV=production
        <br>
        SECRET_KEY=9OLWxND4o83j4K4iuopO
        <br>
    </p>
    <br>
    <br>
    <p>
        <!-- Avoid using the same passwords in other places. -->
        <!-- DEVELOPMENT_ENV_CREDENTIALS: e8f9a4a8b729ffbfb25c564e4708f61a  -->
    </p>
    <br>
    <!--  Apache Flink 1.9.1 - Copyright (C) 2004-2018. All rights reserved. -->
</body>
</html>

flask_internals/templates/dashboard/accounts/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-8">
      <div class="card">

        <form role="form" method="post" action="">
        
          {{ form.hidden_tag() }} 

          <div class="card-header">
            <h5 class="title">Login</h5>

            <h6 class="card-category">
                {% if msg %}
                  <span class="text-danger">{{ msg | safe }}</span>
                {% else %}
                <span>
                  Use default credentials: test / pass
                </span>
                {% endif %}  
            </h6>
          </div>

          <div class="card-body">

              <div class="row">

                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Username</label>
                    {{ form.username(class="form-control") }}
                  </div>
                </div>

              </div>
              <div class="row">

                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Password</label>
                    {{ form.password(class="form-control", type="password") }}
                  </div>
                </div>

              </div>
              
          </div>
          <div class="card-footer">
            <button type="submit" name="login" class="btn btn-fill btn-primary">Login</button>
            &nbsp; &nbsp;
            Don't have an account? <a href="{{ url_for('base_blueprint.register') }}" class="text-primary">Create</a>
          </div>

        </form>

      </div>
    </div>
  </div>
{% endblock content %}
<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

flask_internals/templates/dashboard/accounts/register.html
{% extends "base.html" %}

{% block title %} Register {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

  <div class="row">
    <div class="col-md-8">
      <div class="card">

        <form role="form" method="post" action="">
        

          <div class="card-header">
            <h5 class="title">Register an Admin Account (it's a little buggy) </h5>

            <h6 class="card-category">
                {% if msg %}
                  <span class="text-danger">{{ msg | safe }}</span>
                {% else %}
                  Complete your credentials
                {% endif %}  
            </h6>
          </div>

          <div class="card-body">
              <div class="row">
                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Username</label>
                  <input> </input>
                  </div>
                </div>
              </div>
              <div class="row">
                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Email</label>
                  <input> </input>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="col-md-3 px-md-1">
                  <div class="form-group">
                    <label>Password</label>
                    <input> </input>
                  </div>
                </div>
              </div>
              
          </div>
          <div class="card-footer">
            <button type="submit" name="register" class="btn btn-fill btn-primary">Register</button>
            &nbsp; &nbsp;
          </div>

        </form>

      </div>
    </div>
  </div>

{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

flask_internals/templates/dashboard/login.html
{% extends "layouts/base.html" %}

{% block title %} Login {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

        <div class="row">
          <div class="col-md-8">
            <div class="card">

              <form role="form" method="post" action="">
              
                <div class="card-header">
                  <h5 class="title">Login</h5>

                  <h6 class="card-category">
                      Add your credentials
                  </h6>
                </div>

                <div class="card-body">

                    <div class="row">

                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Username</label>
                          <input class="form-control" id="username_login" name="username" required="" type="text" value="">
                        </div>
                      </div>

                    </div>
                    <div class="row">

                      <div class="col-md-3 px-md-1">
                        <div class="form-group">
                          <label>Password</label>
                          <input class="form-control" id="pwd_login" name="password" required="" type="password" value="">
                        </div>
                      </div>

                    </div>
                    
                </div>
                <div class="card-footer">
                  <button type="submit" name="login" class="btn btn-fill btn-primary">Login</button>
                  &nbsp; &nbsp;
                  Don't have an account? <a href="/register.html" class="text-primary">Create</a>
                </div>

              </form>

            </div>
          </div>
      </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

flask_internals/templates/dashboard/page-403.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 403</h6>
                    <h4 class="card-title">
                        Access Denied - please authenticate
                    </h4>
                    <a href="/login.html" class="btn btn-primary btn-round">Login</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

flask_internals/templates/dashboard/page-404.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 404</h6>
                    <h4 class="card-title">
                        Page not found
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

flask_internals/templates/dashboard/page-500.html
{% extends "layouts/base.html" %}

{% block title %} Page 404 {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Error 500</h6>
                    <h4 class="card-title">
                        Internal Server Error
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

flask_internals/templates/dashboard/page-blank.html
{% extends "layouts/base.html" %}

{% block title %} Page Blank {% endblock %} 

<!-- Specific Page CSS goes HERE  -->
{% block stylesheets %}{% endblock stylesheets %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <div class="card card-profile">
                <div class="card-body">
                    <h6 class="card-category text-gray">Page Blank</h6>
                    <h4 class="card-title">
                        Add your content 
                    </h4>
                    <a href="/" class="btn btn-primary btn-round">Home</a>
                </div>
            </div>
        </div>
    </div>
    
{% endblock content %}

<!-- Specific Page JS goes HERE  -->
{% block javascripts %}{% endblock javascripts %}

flask_internals/templates/includes/navigation.html
      <!-- Navbar -->
      <nav class="navbar navbar-expand-lg navbar-absolute navbar-transparent">
        <div class="container-fluid">
          <div class="navbar-wrapper">
            <div class="navbar-toggle d-inline">
              <button type="button" class="navbar-toggler">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </button>
            </div>
            <a class="navbar-brand" href="javascript:void(0)">Dashboard - Demo</a>
          </div>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
            <span class="navbar-toggler-bar navbar-kebab"></span>
          </button>
          <div class="collapse navbar-collapse" id="navigation">

            <ul class="navbar-nav ml-auto">
              <li class="search-bar input-group">
                <button class="btn btn-link" id="search-button" data-toggle="modal" data-target="#searchModal"><i class="tim-icons icon-zoom-split" ></i>
                  <span class="d-lg-none d-md-block">Search</span>
                </button>
              </li>
              <li class="dropdown nav-item">
                <a href="javascript:void(0)" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="notification d-none d-lg-block d-xl-block"></div>
                  <i class="tim-icons icon-sound-wave"></i>
                  <p class="d-lg-none">
                    Notifications
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-menu-right dropdown-navbar">
                  <li class="nav-link"><a href="#" class="nav-item dropdown-item">Mike John responded to your email</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">You have 5 more tasks</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Your friend Michael is in town</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another notification</a></li>
                  <li class="nav-link"><a href="javascript:void(0)" class="nav-item dropdown-item">Another one</a></li>
                </ul>
              </li>
              <li class="dropdown nav-item">
                <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
                  <div class="photo">
                    <img src="/static/assets/img/anime3.png" alt="Profile Photo">
                  </div>
                  <b class="caret d-none d-lg-block d-xl-block"></b>
                  <p class="d-lg-none">
                    Log out
                  </p>
                </a>
                <ul class="dropdown-menu dropdown-navbar">
                  <li class="nav-link"><a href="/page-user.html" class="nav-item dropdown-item">Profile</a></li>
                  <li class="dropdown-divider"></li>
                  <li class="nav-link">
                    <a href="{{ url_for('main_bp.logout') }}" class="nav-item dropdown-item">Log out</a></li>
                </ul>
              </li>
              <li class="separator d-lg-none"></li>
            </ul>

          </div>
        </div>
      </nav>
      <div class="modal modal-search fade" id="searchModal" tabindex="-1" role="dialog" aria-labelledby="searchModal" aria-hidden="true">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <input type="text" class="form-control" id="inlineFormInputGroup" placeholder="SEARCH">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
      </div>
      <!-- End Navbar -->

flask_internals/templates/includes/sidebar.html
    <div class="sidebar">
      <div class="sidebar-wrapper">
        <div class="logo">
          <a target="_blank" rel="sponsored noopener noreferrer" 
             href="https://appseed.us/admin-dashboards/flask-dashboard-black" class="simple-text logo-mini">
            LG
          </a>
          <a target="_blank" rel="sponsored noopener noreferrer" 
             href="https://appseed.us/admin-dashboards/flask-dashboard-black" class="simple-text logo-normal">
            Admin Menu
          </a>
        </div>

        <ul class="nav">
          {% if current_user.is_authenticated %}
          <li class="{% if 'index' in segment %} active {% endif %}">
            <a href="/Management/login_form/admin_login_v2/dashboard/index.html">
              <i class="tim-icons icon-chart-pie-36"></i>
              <p>Dashboard</p>
            </a>
          </li>
          <li class="{% if 'icons' in segment %} active {% endif %}">
            <a href="/Management/login_form/admin_login_v2/dashboard/ui-icons.html">
              <i class="tim-icons icon-atom"></i>
              <p>Icons</p>
            </a>
          </li>
          <li class="{% if 'maps' in segment %} active {% endif %}">
            <a href="/Management/login_form/admin_login_v2/dashboard/ui-maps.html">
              <i class="tim-icons icon-pin"></i>
              <p>Maps</p>
            </a>
          </li>
          <li class="{% if 'notifications' in segment %} active {% endif %}">
            <a href="/Management/login_form/admin_login_v2/dashboard/ui-notifications.html">
              <i class="tim-icons icon-bell-55"></i>
              <p>Notifications</p>
            </a>
          </li>
          <li class="{% if 'page-user' in segment %} active {% endif %}">
            <a href="/Management/login_form/admin_login_v2/dashboard/page-user.html">
              <i class="tim-icons icon-single-02"></i>
              <p>User Profile</p>
            </a>
          </li>
          <li class="{% if 'register' in segment %} active {% endif %}">
            <a href="/Management/login_form/admin_login_v2/dashboard/register?register=" >
              <i class="tim-icons icon-user-run"></i>
              <p>Register</p>
            </a>
          </li>
          <li>
            <a href="{{ url_for('main_bp.logout') }}" >
              <i class="tim-icons icon-button-power"></i>
              <p>Logout</p>
            </a>
          </li>
          {% else %}
          <li class="active">
            <a target="_blank" 
               href="https://appseed.us/admin-dashboards/flask-dashboard-black-pro">
              <i class="tim-icons icon-spaceship"></i>            
            </a>
          </li>   
          {% endif %}
        </ul>
        
      </div>
    </div>

flask_internals/templates/robots.html
<html>
    <body>
        <div>
            {% include 'robots.txt' %}
        </div>
        </body>
</html>